#!/usr/bin/env bash
# Local SDK stub generation without CI / network buf plugins.
#
# Generates:
#   - TypeScript stubs -> sdks/typescript/src/gen   (needs Node deps with
#     @bufbuild/protoc-gen-es installed under sdks/typescript)
#   - Python stubs     -> sdks/python/longtrader_sdk/proto (needs python3 +
#     grpcio-tools)
#
# Steps whose toolchain is unavailable are skipped with a yellow notice;
# the script never fails the whole run because of one missing toolchain.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

YELLOW='\033[33m'
GREEN='\033[32m'
RESET='\033[0m'

RAN=()
SKIPPED=()

note_skip() {
  echo -e "${YELLOW}[skip]${RESET} $1"
  SKIPPED+=("$1")
}

note_ok() {
  echo -e "${GREEN}[ok]${RESET} $1"
  RAN+=("$1")
}

# ---------------------------------------------------------------------------
# Step TS: TypeScript stubs via repo-local protoc-gen-es (no remote plugin)
# ---------------------------------------------------------------------------
TS_DIR="${ROOT}/sdks/typescript"
TS_PLUGIN="${TS_DIR}/node_modules/@bufbuild/protoc-gen-es"

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  note_skip "TypeScript codegen (node/npm not found)"
elif [ ! -d "${TS_PLUGIN}" ]; then
  # Plugin missing: try to restore node deps from lockfile or registry.
  echo -e "${YELLOW}[notice]${RESET} @bufbuild/protoc-gen-es missing; running npm install in sdks/typescript"
  if [ -f "${TS_DIR}/package-lock.json" ]; then
    NPM_ARGS=(ci --no-audit --no-fund)
  else
    NPM_ARGS=(install --no-audit --no-fund)
  fi
  if (cd "${TS_DIR}" && npm "${NPM_ARGS[@]}") && [ -d "${TS_PLUGIN}" ]; then
    : # fall through to generation below
  else
    note_skip "TypeScript codegen (npm could not provide @bufbuild/protoc-gen-es)"
  fi
fi

if [ -d "${TS_PLUGIN}" ]; then
  # Absolute plugin path so the template works regardless of buf's cwd.
  TS_PLUGIN_ABS="$(cd "${TS_PLUGIN}" && pwd)"
  cat > "${ROOT}/proto/buf.gen.ts.local.yaml" <<EOF
version: v2
# Local TypeScript codegen using the repo-local protoc-gen-es (offline-safe).
# Generated by scripts/gen-proto.sh; do not commit hand edits.
clean: true
plugins:
  - local: ["node", "${TS_PLUGIN_ABS}/bin/protoc-gen-es"]
    out: ../sdks/typescript/src/gen
EOF
  if (cd "${ROOT}/proto" && buf generate --template buf.gen.ts.local.yaml); then
    note_ok "TypeScript stubs -> sdks/typescript/src/gen"
  else
    note_skip "TypeScript codegen (buf generate failed; plugin version mismatch?)"
  fi
fi

# ---------------------------------------------------------------------------
# Step PY: Python stubs via grpcio-tools (protoc + mypy .pyi)
# ---------------------------------------------------------------------------
PY_OUT="sdks/python/longtrader_sdk/proto"

if ! command -v python3 >/dev/null 2>&1; then
  note_skip "Python codegen (python3 not found)"
elif ! python3 -c "import grpc_tools" >/dev/null 2>&1; then
  echo -e "${YELLOW}[notice]${RESET} grpcio-tools missing; running pip3 install --quiet grpcio-tools"
  if pip3 install --quiet grpcio-tools && python3 -c "import grpc_tools" >/dev/null 2>&1; then
    : # fall through to generation below
  else
    note_skip "Python codegen (could not install grpcio-tools)"
  fi
fi

if python3 -c "import grpc_tools" >/dev/null 2>&1; then
  mkdir -p "${ROOT}/${PY_OUT}"
  if [ ! -f "${ROOT}/${PY_OUT}/__init__.py" ]; then
    printf '"""Generated protobuf stubs; do not edit by hand."""\n' > "${ROOT}/${PY_OUT}/__init__.py"
  fi
  cd "${ROOT}"
  # shellcheck disable=SC2046  # word splitting is intended for the file list
  python3 -m grpc_tools.protoc -I proto \
    --python_out="${PY_OUT}" \
    --pyi_out="${PY_OUT}" \
    $(find proto -name '*.proto')
  note_ok "Python stubs -> ${PY_OUT}"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== gen-proto summary ==="
if [ "${#RAN[@]}" -gt 0 ]; then
  for item in "${RAN[@]}"; do echo -e "  ${GREEN}ran:${RESET} ${item}"; done
fi
if [ "${#SKIPPED[@]}" -gt 0 ]; then
  for item in "${SKIPPED[@]}"; do echo -e "  ${YELLOW}skipped:${RESET} ${item}"; done
fi
